name: "run tests, lint, build"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: npm install, build, and test
        run: |
          npm ci
          npm run lint
          npm run ts-check
          # npm run build
          npm t
        env:
          CI: true
          FROM_PHONE_NUMBER_ID: ${{ secrets.FROM_PHONE_NUMBER_ID }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          VERSION: ${{ secrets.VERSION }}
          TO: ${{ secrets.TO }}
          WEBHOOK_VERIFY_TOKEN: ${{ secrets.WEBHOOK_VERIFY_TOKEN }}
          WEBHOOK_PATH: ${{ secrets.WEBHOOK_PATH }}